import type { NextPage } from 'next'
import Head from 'next/head'
import Card from 'https://framer.com/m/Card-iviQ.js@swzyETDVEgZwhViZsNKA'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Card />
      </main>
    </div>
  )
}

export default Home
